name: E2E Tests DApps playground

on:
  workflow_dispatch:
    inputs:

run-name: "Checking Pages | os: Linux | browser: 'chrome' | #${{ github.run_number }}"

env:
  RUN: ${{ github.run_number }}
  DISPLAY: ':99.0'

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.readEnvironment.outputs.nodeVersion }}
          cache: 'yarn'
      - name: Node modules cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn install --check-cache --frozen-lockfile --non-interactive --logevel=error
      - name: Execute E2E tests
        id: e2e-tests
        continue-on-error: true
        run: |
          yarn test
      - name: Publish artifacts (logs, reports, screenshots)
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-results
          path: |
                  ./allure-results
          retention-days: 20
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Create Playwright Test Results History
        uses: PavanMudigonda/allure-html-reporter-github-pages@v1.0
        if: always()
        id: allure-report
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
#      - name: Create Allure report with history
#        uses: simple-elf/allure-report-action@master
#        if: always()
#        id: allure-report
#        with:
#          allure_results: allure-results
#          gh_pages: gh-pages
#          allure_report: allure-report
#          allure_history: allure-history
#          keep_reports: 20


      - name: Encrypt report
        if: always()
        continue-on-error: true
        env:
          env.STATICRYPT_PASSWORD: ${{ secrets.STATICRYPT_PASSWORD }}
        run: |
          sudo npx staticrypt ./allure-history/${{ github.run_number }}/index.html -d . -p nwb*pwj6RKZ3cvyfay
          sudo npx staticrypt ./allure-history/index.html -d . -p nwb*pwj6RKZ3cvyfay
#      - name: Setup upterm session
#        uses: lhotari/action-upterm@v1
      - name: Deploy report to GH Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.9.3
        #        env:
        #          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #          PUBLISH_BRANCH: gh-pages
        #          PUBLISH_DIR: allure-history
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          destination_dir: docs
